//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NesaBotDesktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class DiscordSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DiscordSettings defaultInstance = ((DiscordSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DiscordSettings())));
        
        public static DiscordSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection JoinedChanels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["JoinedChanels"]));
            }
            set {
                this["JoinedChanels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DmUsers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DmUsers"]));
            }
            set {
                this["DmUsers"] = value;
            }
        }
    }
}
